version: '3'
services:
  heartbeat-publisher-service:
    build:
      context: heartbeat-publisher-service
    depends_on:
      - apache-activemq
    environment:
      ACTIVEMQ_URL: ${ACTIVEMQ_URL}
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      HEARTBEAT_PUBLISHER_SERVICE_CLIENT_ID: heartbeat-publisher
  first-heartbeat-subscriber-service:
    build:
      context: heartbeat-subscriber-service
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - apache-activemq
    environment:
      ACTIVEMQ_URL: ${ACTIVEMQ_URL}
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      HEARTBEAT_SUBSCRIBER_SERVICE_CLIENT_GROUP: first-heartbeat-subscriber
  second-heartbeat-subscriber-service:
    build:
      context: heartbeat-subscriber-service
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - apache-activemq
    environment:
      ACTIVEMQ_URL: ${ACTIVEMQ_URL}
      ACTIVEMQ_USER: ${ACTIVEMQ_USER}
      ACTIVEMQ_PASSWORD: ${ACTIVEMQ_PASSWORD}
      HEARTBEAT_SUBSCRIBER_SERVICE_CLIENT_GROUP: second-heartbeat-subscriber
  apache-activemq:
    build:
      context: apache-activemq
    ports:
      - 8161:8161
      - 61616:61616
